import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Pause, Play, RotateCcw, Volume2, VolumeX, ArrowLeft, ArrowRight, Zap, Camera } from 'lucide-react';
import { RaceEngine, initial, FINISH } from './race-engine';
const zones = ['강남 · 테헤란로', '청담 · 도산대로', '반포 · 한강대로', '남산 · 도심 순환'];
export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),engine=useRef<RaceEngine|null>(null);
 const [hud,setHud]=useState(initial),[muted,setMuted]=useState(true),[color,setColor]=useState('#f31931');
 const start=()=>engine.current?.start();
 const pause=()=>engine.current?.pause();
 const toggleSound=()=>{const muted=engine.current?.setSound();if(muted!==undefined)setMuted(muted);};
 useEffect(()=>{
  try{engine.current=new RaceEngine(canvas.current!,setHud);}catch(error){console.error(error);setHud(s=>({...s,error:'3D 화면을 시작하지 못했습니다. WebGL을 지원하는 브라우저에서 하드웨어 가속을 켜 주세요.'}));}
  return()=>{engine.current?.dispose();engine.current=null;};
 },[]);
 const touch=(key:string)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.currentTarget.setPointerCapture(e.pointerId);engine.current?.keys.add(key);},onPointerUp:()=>engine.current?.keys.delete(key),onPointerCancel:()=>engine.current?.keys.delete(key),onLostPointerCapture:()=>engine.current?.keys.delete(key)});
 const active=hud.mode==='racing'||hud.mode==='paused';
 return <main className={`game-shell ${hud.mode} ${hud.boost?'boosting':''}`}>
  <canvas ref={canvas} aria-label="Ferrari 458 Italia 3D 서울 도심 레이싱"/>
  <div className="grain"/>
  <header className="topbar"><a className="brand" href={import.meta.env.BASE_URL}>S<span>／</span>MR <small>SEOUL MIDNIGHT RUN</small></a><div className="top-actions"><span className="live-dot"/> <span className="edition">3D / NIGHT DRIVE</span><button onClick={toggleSound} aria-label={muted?'소리 켜기':'소리 끄기'}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button>{active&&<button onClick={()=>engine.current?.changeCamera()} aria-label="카메라 시점 변경"><Camera size={19}/></button>}{active&&<button onClick={pause} aria-label={hud.mode==='paused'?'계속하기':'일시정지'}>{hud.mode==='paused'?<Play size={19}/>:<Pause size={19}/>}</button>}</div></header>
  {hud.mode==='ready'&&<><section className="start-panel"><div className="eyebrow"><span/> SEOUL / NIGHT RUN 02</div><h1>서울의 밤.<br/><em>458 ITALIA.</em></h1><p>V8의 울림, 네온에 물든 도심.<br/>페라리의 운전석에서 4.2km를 질주하세요.</p><div className="paint-options" aria-label="차량 색상">{[['#f31931','로쏘 레드'],['#f7bd28','레이싱 옐로'],['#d5dfeb','실버'],['#172136','미드나이트 블루']].map(([value,label])=><button key={value} aria-label={label} aria-pressed={color===value} title={label} style={{background:value}} onClick={()=>{setColor(value);engine.current?.setColor(value);}}/>)}</div><button className="start-button" disabled={!hud.loaded||!!hud.error} onClick={start}>{hud.error?'3D 로드 실패':hud.loaded?'엔진 시동 · 레이스 시작':'Ferrari 불러오는 중…'} <ArrowUpRight size={24}/></button><div className="enter-hint">{hud.error||'ENTER 출발 · WASD 주행 · SPACE 부스트'}</div></section><aside className="car-spec"><span>FERRARI</span><h2>458 <i>Italia</i></h2><div><b>V8<small>4.5 L ENGINE</small></b><b>570<small>CV / POWER</small></b><b>&lt;3.4<small>SEC / 0–100*</small></b></div><p><a href="https://www.ferrari.com/en-MG/history/moments/2009/benchmark-car/more" target="_blank" rel="noreferrer">*차량 제원</a> · 게임은 아케이드 주행</p></aside><a className="model-credit" href="https://threejs.org/examples/webgl_materials_car.html" target="_blank" rel="noreferrer">458 Italia model / vicent091036 · Three.js ↗</a></>}
  {active&&<><div className="race-top"><div><span className="eyebrow">CURRENT SECTOR / 0{Math.min(4,Math.floor(hud.distance/1050)+1)}</span><h2>{zones[Math.min(3,Math.floor(hud.distance/1050))]}</h2></div><div className="timer"><span>RACE TIME</span>{formatTime(hud.time)}</div></div><div className="route-progress"><i style={{width:`${hud.distance/FINISH*100}%`}}/></div><div className="telemetry"><div className="speed"><b>{Math.round(hud.speed).toString().padStart(3,'0')}</b><span>KM/H<small className="gear">GEAR {hud.gear}</small></span></div><div className="meters"><label><span>BOOST <Zap size={12}/></span><span>{Math.round(hud.nitro)}%</span></label><div><i style={{width:`${hud.nitro}%`}}/></div><label><span>차량 상태</span><span>{Math.round(hud.health)}%</span></label><div className="health"><i style={{width:`${hud.health}%`}}/></div></div></div><div className="remaining"><span>TO FINISH</span><strong>{((FINISH-hud.distance)/1000).toFixed(2)}<small> km</small></strong></div></>}
  {hud.mode==='paused'&&<div className="overlay"><section className="result"><span className="eyebrow">TAKE A BREATHER</span><h2>잠시 쉬어가기</h2><p>준비되면 서울의 밤을 계속 달리세요.</p><button className="start-button" onClick={pause}>계속 달리기 <Play size={20}/></button><button className="text-button" onClick={start}>처음부터 다시 시작</button></section></div>}
  {hud.mode==='finished'&&<div className="overlay"><section className="result"><span className="eyebrow">{hud.health>0?'CIRCUIT COMPLETE':'RUN ENDED'}</span><h2>{hud.health>0?'서울의 밤을 완주했습니다.':'이번 주행은 여기까지.'}</h2><p>{hud.health>0?'다음 레이스에서 새로운 기록에 도전하세요.':'차량이 파손되었습니다. 교통량을 살피며 다시 도전하세요.'}</p><div className="result-stats"><div><span>주행 시간</span><b>{formatTime(hud.time)}</b></div><div><span>주행 거리</span><b>{(hud.distance/1000).toFixed(2)} km</b></div><div><span>추월</span><b>{hud.passed}</b></div></div><button className="start-button" onClick={start}>다시 달리기 <RotateCcw size={20}/></button></section></div>}
  <footer className="bottom-bar"><div className="coordinates">37°33′ N &nbsp; 126°58′ E <span>서울, 대한민국</span></div><div className="keyboard-guide"><span><kbd>W</kbd><kbd>↑</kbd> 가속</span><span><kbd>A</kbd><kbd>D</kbd> 조향</span><span><kbd>S</kbd> 브레이크</span><span><kbd>SPACE</kbd> 부스트</span><span><kbd>C</kbd> 시점 <kbd>P</kbd> 일시정지</span></div><span className="circuit-label">FERRARI 458 ITALIA <i>↗</i></span></footer>
  {hud.mode==='racing'&&<div className="touch-controls"><div><button aria-label="왼쪽으로 조향" {...touch('arrowleft')}><ArrowLeft/></button><button aria-label="오른쪽으로 조향" {...touch('arrowright')}><ArrowRight/></button></div><div><button {...touch('arrowdown')}>제동</button><button className="boost-touch" {...touch(' ')}><Zap size={19}/></button><button {...touch('arrowup')}>가속</button></div></div>}
 </main>;
}
function formatTime(t:number){return `${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}.${Math.floor(t%1*100).toString().padStart(2,'0')}`;}
